#!/bin/bash

#SBATCH --job-name=umap      # Job name
#SBATCH --cpus-per-task=8        # Schedule one core
#SBATCH --time=10:00:00        # Run time (hh:mm:ss) - run for one hour max
#SBATCH --mem=100G        # Memory per CPU core

# Set the output file name dynamically
OUTPUT_FILE="umap_$1.out"

# Redirect the script's output to the dynamic file
exec > "$OUTPUT_FILE" 2>&1

# Print out the hostname of the node the job is running on
python run_umap.py $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
