#!/bin/bash

#SBATCH --job-name=merge       # Job name
#SBATCH --cpus-per-task=4        # Schedule one core
#SBATCH --time=1:00:00        # Run time (hh:mm:ss) - run for one hour max
#SBATCH --mem=100G

# Set the output file name dynamically
OUTPUT_FILE="merge-embeddings_$1.out"

# Redirect the script's output to the dynamic file
exec > "$OUTPUT_FILE" 2>&1

# Print out the hostname of the node the job is running on
python merge_embeddings.py $1 $2
