#!/bin/bash

#SBATCH --job-name=unzip          # Job name
#SBATCH --cpus-per-task=4        # Schedule 16 cores
#SBATCH --time=30:00              # Run time (hh:mm:ss) - run for 30 minutes max

# Set the output file name dynamically
OUTPUT_FILE="unzip_files_$1.out"

# Redirect the script's output to the dynamic file
exec > "$OUTPUT_FILE" 2>&1

# Print out the hostname of the node the job is running on
python extract_files.py $1 $2